# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e235f388fb53a0f29c0adc7bfc25313c0019f163241f44921a26e5a68d16d1a595adfa82407672b90e13a456d80e22bfdefe02c3997ad4997b40b526dff303db

test:
  secret_key_base: 8780a0ffa8eb73e34b5585ce520e01a5cbb43493c6be5ee90c69e80f991a171206e5a527f246b3e5caa55196f07b8c6daabd617fdbdd36bf3ce9e65b3a272976

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
